"""Generate paper/tables_generated.tex from sweep results.

Every number in the paper's tables is produced by this script from the
exhaustive sweep data; nothing is typed by hand.
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.analyze import classes, load, split_witnesses
from src.digraph import parse_digraph6
from src.maghom import magnitude_homology_ranks

ROOT = Path(__file__).resolve().parents[1]


def class_count_table():
    lines = [
        r"\begin{tabular}{lrrrrrrr}",
        r"\toprule",
        r"$n$ & digraphs & D-WL & $\MH_{k\le 3}$ & dist & $\PH_{\le 2}$ & $\RH_{\le 3}$ & all three \\",
        r"\midrule",
    ]
    for n in (3, 4, 5):
        rows = load(n)
        cnt = {
            "dwl": len(classes(rows, "dwl_key")),
            "mh": len(classes(rows, "mh_key")),
            "dist": len(classes(rows, "dist_key")),
            "ph": len(classes(rows, "ph_key")),
            "rh": len(classes(rows, "rh_key")),
            "all": len(classes(rows, "all_hom_key")),
        }
        lines.append(
            f"{n} & {len(rows)} & {cnt['dwl']} & {cnt['mh']} & {cnt['dist']}"
            f" & {cnt['ph']} & {cnt['rh']} & {cnt['all']} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


def split_table():
    labels = [
        ("dwl_key", "mh_key", r"D-WL-equal, $\MH$-different"),
        ("dwl_key", "ph_key", r"D-WL-equal, $\PH$-different"),
        ("dwl_key", "dist_key", r"D-WL-equal, dist-different"),
        ("dist_key", "dwl_key", r"dist-equal, D-WL-different"),
        ("mh_key", "dwl_key", r"$\MH$-equal, D-WL-different"),
        ("mh_key", "ph_key", r"$\MH$-equal, $\PH$-different"),
        ("ph_key", "mh_key", r"$\PH$-equal, $\MH$-different"),
        ("ph_key", "rh_key", r"$\PH$-equal, $\RH$-different"),
        ("all_hom_key", "dwl_key", r"$\MH{+}\PH{+}\RH$-equal, D-WL-different"),
    ]
    per_n = {}
    for n in (3, 4, 5):
        rows = load(n)
        for r in rows:
            r["mhph_key"] = r["mh_key"] + "|" + r["ph_key"]
        vals = {}
        for ki, kj, _ in labels:
            vals[(ki, kj)] = split_witnesses(rows, ki, kj)[0]
        vals[("mhph_key", "rh_key")] = split_witnesses(rows, "mhph_key", "rh_key")[0]
        per_n[n] = vals
    lines = [
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"relation & $n=3$ & $n=4$ & $n=5$ \\",
        r"\midrule",
    ]
    for ki, kj, lab in labels:
        lines.append(
            f"{lab} & {per_n[3][(ki,kj)]} & {per_n[4][(ki,kj)]} & {per_n[5][(ki,kj)]} \\\\"
        )
    lines.append(
        r"$\MH{+}\PH$-equal, $\RH$-different & "
        + " & ".join(str(per_n[n][("mhph_key", "rh_key")]) for n in (3, 4, 5))
        + r" \\"
    )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


def mh_table(g6, kmax=3):
    n, arcs = parse_digraph6(g6)
    mh = magnitude_homology_ranks(n, arcs, kmax=kmax)
    items = sorted(mh.items())
    cells = ", ".join(f"$\\MH_{{{k},{l}}}={r}$" for (k, l), r in items)
    return cells


def beyond_distance_pairs():
    """The three F-classes at n=5 (D-WL & dist-equal, MH-different)."""
    rows = load(5)
    d = classes(rows, "dwl_key")
    out = []
    for group in d.values():
        if len(group) < 2:
            continue
        sub = defaultdict(list)
        for r in group:
            sub[r["dist_key"]].append(r)
        for g2 in sub.values():
            if len(g2) < 2:
                continue
            sub2 = defaultdict(list)
            for r in g2:
                sub2[r["mh_key"]].append(r)
            if len(sub2) > 1:
                reps = [v[0] for v in sub2.values()][:2]
                out.append((reps[0]["g6"], reps[1]["g6"]))
    return out


def main():
    parts = [
        "% AUTO-GENERATED by src/gen_tables.py -- do not edit by hand",
        "\\newcommand{\\tabclasscounts}{%\n" + class_count_table() + "}",
        "\\newcommand{\\tabsplits}{%\n" + split_table() + "}",
        "\\newcommand{\\mhcfour}{" + mh_table("&CGS_") + "}",
        "\\newcommand{\\mhdigons}{" + mh_table("&CGWO") + "}",
        "\\newcommand{\\mhcirc}{" + mh_table("&DKMME?") + "}",
        "\\newcommand{\\mhcirctwin}{" + mh_table("&DKLMI?") + "}",
    ]
    def tex_g6(s):
        return "\\texttt{" + s.replace("&", "\\&").replace("_", "\\_") + "}"

    pairs = beyond_distance_pairs()
    plines = []
    for a, b in pairs:
        na, aa = parse_digraph6(a)
        nb, ab = parse_digraph6(b)
        plines.append(
            f"{tex_g6(a)} vs {tex_g6(b)}: "
            f"arcs $\\{{{', '.join(f'{u}{v}' for u, v in sorted(aa))}\\}}$ vs "
            f"$\\{{{', '.join(f'{u}{v}' for u, v in sorted(ab))}\\}}$"
        )
    parts.append("\\newcommand{\\beyonddistpairs}{" + " \\par ".join(plines) + "}")
    out = ROOT / "paper" / "tables_generated.tex"
    out.write_text("\n\n".join(parts) + "\n")
    print(f"wrote {out}")
    for a, b in pairs:
        print("F-pair:", a, b)


if __name__ == "__main__":
    main()
